#!/bin/bash
CONF_FILE="/etc/default/tftpd-hpa"
BACKUP_FILE="/etc/default/tftpd-hpa.bak"

if [ -f "$CONF_FILE" ]; then
    if [ ! -f "$BACKUP_FILE" ]; then
        cp "$CONF_FILE" "$BACKUP_FILE"
        echo "TFTP Manager: Создан бэкап оригинального конфига ($BACKUP_FILE)."
    fi

    # Включаем verbose
    if ! grep -q "verbose" "$CONF_FILE"; then
        sed -i 's/TFTP_OPTIONS="\(.*\)"/TFTP_OPTIONS="\1 --verbose"/' "$CONF_FILE"
    fi
fi

systemctl stop tftpd-hpa
systemctl disable tftpd-hpa
echo "TFTP Manager: Сервер tftpd-hpa переведен в ручной режим управления."

chmod +x /usr/local/bin/tftpd-manager.sh
exit 0
