name: Build and Release

on:
  push:
    tags:
      - 'v*' # Срабатывает при пуше тегов типа v1.0, v1.1 и т.д.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Packages
        run: |
          # Даем права на скрипт сборки
          chmod +x build.sh
          # Запускаем твой скрипт сборки
          ./build.sh
          
          # Определяем имена файлов для загрузки (вытягиваем из файловой системы)
          echo "DEB_FILE=$(ls *.deb)" >> $GITHUB_ENV
          echo "TAR_FILE=$(ls *.tar.gz)" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.DEB_FILE }}
            ${{ env.TAR_FILE }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
